setup: Fix the parse requirements step
AFAICT, there has been a breaking change in the pip internal in the past. And that code
is old enough to be impacted by it.

With the previous version:
```
$ nix develop
warning: Git tree '/home/tony/repo/private/ardumont-pytools' is dirty
warning: unknown setting 'experimental-features'
building '/nix/store/dgwmaz1gm72n8g2npyqqi20g8hkqkllw-python3.8-python_tvmaze-71c799c692ab24f1c6f1a748144ce6ac83668a1d.drv'...
builder for '/nix/store/dgwmaz1gm72n8g2npyqqi20g8hkqkllw-python3.8-python_tvmaze-71c799c692ab24f1c6f1a748144ce6ac83668a1d.drv' failed with exit code 1; last 10 log lines:
  configuring
  no configure script, doing nothing
  building
  Executing setuptoolsBuildPhase
  Traceback (most recent call last):
    File "nix_run_setup", line 8, in <module>
      exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\\r\\n', '\\n'), __file__, 'exec'))
    File "setup.py", line 6, in <module>
      from pip.req import parse_requirements
  ModuleNotFoundError: No module named 'pip.req'
cannot build derivation '/nix/store/b876gkiwcblnws41vnrb3jrbl3nj5dk5-python3.8-ardumont.pytools.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/07qqmiifv9fdgkdqhmf86q9g1vh4hvk3-pytools-env-env.drv': 1 dependencies couldn't be built
```